apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asaban
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: asaban
        version: v1
    spec:
      containers:
      - name: asabanrepo
        image: fra.ocir.io/oraseemeail/asabanrepo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: ocir
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: asaban
  labels:
    app: asaban
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: asaban
